apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fnfkiegy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-fnfkiegy:b5bf82d385f02f8ecb27f498a310eee46d53d88b@sha256:1137711955dbc7820b84e2225d080ca5b064c8ac15078a2c7e41b0a632ce4e0f
          name: container-image
